site_name: TACC HPC Documentation
site_description: TACC HPC Documentation
site_author: Susan Lindsey
site_url: https://readthedocs.tacc.utexas.edu

theme:
    name: readthedocs


nav:
  - Fiddling : testingextensions.md
  - HPC :
    - Maverick2: hpcugs/2mav/maverick2.md
#   - Corral: hpcugs/corral/corral.md
#   - Frontera: hpcugs/frontera/frontera.md
#   - Lonestar6: hpcugs/6lonestar/lonestar6.md
#   - Ranch: hpcugs/ranch/ranchsrc.md
#   - Stallion: hpcugs/stallion/stallionsrc.md
#   - Stampede2: hpcugs/stampede2/stampede2.md
  - Software :
    - GROMACS: softwareugs/gromacs.md
#    - Gaussian: softwareugs/gaussian.md
#    - Tensorflow: softwareugs/tensorflow.md
#    - VASP: softwareugs/vasp.md
  - Tutorials :
    - Managing I/O at TACC: tutorials/managingio.md
#    - Remote Desktop Access: tutorials/remotedesktopaccess.md

markdown_extensions:
 - tables
 - admonition
 - attr_list
 - abbr

plugins:
  - search
  - macros # allows {% include ... %} (and macros)
#  - with-pdf:
#      copyright: TACC
#      cover_subtitle: TACC User Guide
#      toc_title: TACC User Guide
#      output_path: docs/user-guide.pdf
