site_name: TACC HPC Documentation
site_description: TACC HPC Documentation
site_author: Susan Lindsey
site_url: https://docs.tacc.utexas.edu
repo_url: https://github.com/TACC/TACC-Docs
edit_uri: edit/main/docs/

theme:
    name: readthedocs
    custom_dir: themes/readthedocs

extra_css:
    - css/core-styles.css
    - css/tacc-docs.css

# These are not loaded automatically (TACC/TACC-Docs#3)
# SEE: /themes/readthedocs/main.html @ "block scripts"
extra_javascript:
    - js/setTargetForExternalLinks.js

nav:
  - Fiddling : 
    - Testing Extensions: testingextensions.md
    - Code Examples: code-examples.md
  - HPC :
    - Corral: hpc/corral.md
    - Frontera: hpc/frontera.md
    - Lonestar6: hpc/lonestar6.md
    - Maverick2: hpc/maverick2.md
    - Ranch: hpc/ranch.md
    - Stampede2: hpc/stampede2.md
#   - Stallion: hpc/stallion/stallion.md
  - Software :
    - ABAQUS: software/abaqus.md
    - ANSYS: software/ansys.md
    - AlphaFold : software/alphafold.md
    - CD Tools: software/cdtools.md
    - Gaussian: software/gaussian.md
    - GROMACS: software/gromacs.md
    - idev: software/idev.md
    - IRODS: software/irods.md
    - LAMMPS: software/lammps.md
    - Launcher: software/launcher.md
    - MATLAB: software/matlab.md
    - NAMD: software/namd.md
    - OpenFOAM: software/openfoam.md
#   - Paraview VisIt: software/paraview-visit.md
    - Quantum Espresso: software/quantumespresso.md 
    - REMORA: software/remora.md
    - TAU: software/tau.md
    - Tensorflow: software/tensorflow.md
    - VASP: software/vasp.md
  - Tutorials :
    - Access Control Lists: tutorials/acls.md
    - Bash Quick Start Guide: tutorials/bashstartup.md
    - BLAS/LAPACK: tutorials/blas-lapack.md
    - DDT Debugger: tutorials/ddt.md
    - Grid Community Toolkit: tutorials/gridcommunitytoolkit.md
    - Managing I/O: tutorials/managingio.md
    - MAP: tutorials/map.md
    - Modules/LMod: tutorials/modules.md
    - Multi-Factor Authentication: tutorials/mfa.md
    - Remote Desktop Access: tutorials/remotedesktopaccess.md
    - Sharing Project Files: tutorials/sharingprojectfiles.md
    - TACC Analysis Portal: tutorials/TAP.md


markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr
  # Some extensions are pre-enabled by MkDocs
  # https://github.com/mkdocs/mkdocs/blob/1.4.2/docs/user-guide/configuration.md#markdown_extensions
#  - meta
#  - toc
#  - tables
#  - fenced_code

plugins:
  - search
  - macros # allows {% include ... %} (and macros)
#  - with-pdf:
#      copyright: TACC
#      cover_subtitle: TACC User Guide
#      toc_title: TACC User Guide
#      output_path: docs/user-guide.pdf
